### PR TITLE
Update to actix 0.10 and actix-web 3

### PR DESCRIPTION
**Pull request by cirm**
- Bumped actix to 0.10
- Bumped actix-web to 3
- Bumped this crate to 0.3.1
- Updated actix-web example

### CODE REVIEW

**Comment by cirm** [comment]
@chris-ricketts Hey - is there anything wrong with this or could we get it merged? Thank you.

**Comment by chris-ricketts** [comment]
Hi @cirm - thanks for the PR and apologies for the delay in responding.

It all looks good. I'll merge and publish today. 
I'm assuming you've been using your branch and its all working.

I haven't used Actix since before A/A stabilized, so I am not familiar with the current API.

**Comment by robjtede** [comment]
@chris-ricketts we could consider adopting this into the official actix-extras repo if you are no longer developing it?

**Comment by chris-ricketts** [comment]
@robjtede I'd be happy for it to be included in actix-extras. 

I've created an issue for it #14 to continue this conversation.

**Review by JohnTitor — COMMENTED** [review]
~~Looks good, thanks!~~ Oops, I sent a review to wrong PR :P Ignore me!

**Pull request merged**
